services:
  web:
    build: .
    # O comando agora aplica migrations E junta os estáticos ao iniciar
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /app/__pycache__

      - /app/venv
      # volumes persistentes continuam aqui
      - django_media:/app/media
      - django_static:/app/static
      - django_db:/app/db_data
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-1}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

volumes:
  django_media:
  django_static:
  django_db: