# Generated by Django 6.0.5 on 2026-06-14 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acordo',
            name='entregue',
        ),
        migrations.AddField(
            model_name='acordo',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Pagamento Online (PIX, Cartão, Transferência)'), ('ENTREGA', 'Efetuar pagamento na entrega')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='status',
            field=models.CharField(choices=[('PROPOSTA', 'Proposta Enviada'), ('RECUSADO', 'Não Aceito pelo Gerador'), ('ACEITO', 'Aceito (Aguardando Definição de Pagamento)'), ('AGUARDANDO_VALIDACAO', 'Aguardando Validação do Pagamento Online'), ('TRANSPORTE_LIBERADO', 'Transporte Liberado (Aguardando Envio)'), ('EM_TRANSPORTE', 'Material em Transporte'), ('CONCLUIDO', 'Material Recolhido / Processo Concluído')], default='PROPOSTA', max_length=25),
        ),
        migrations.AddField(
            model_name='obra',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='obras/'),
        ),
        migrations.AlterField(
            model_name='acordo',
            name='comprovante_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Disponível para Propostas'), ('EM_NEGOCIACAO', 'Em Negociação'), ('EM_TRANSPORTE', 'Material em Transporte'), ('CONCLUIDO', 'Finalizada')], default='ATIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')])),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acordo')),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
