# Generated by Django 6.0.5 on 2026-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acordo',
            name='entregue',
        ),
        migrations.AddField(
            model_name='acordo',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Pagamento Online (PIX, Cartão, Transferência)'), ('ENTREGA', 'Efetuar pagamento na entrega')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='status',
            field=models.CharField(choices=[('PROPOSTA', 'Proposta Enviada'), ('RECUSADO', 'Não Aceito pelo Gerador'), ('ACEITO', 'Aceito (Aguardando Definição de Pagamento)'), ('AGUARDANDO_VALIDACAO', 'Aguardando Validação do Pagamento Online'), ('TRANSPORTE_LIBERADO', 'Transporte Liberado (Aguardando Envio)'), ('EM_TRANSPORTE', 'Material em Transporte'), ('CONCLUIDO', 'Material Recolhido / Processo Concluído')], default='PROPOSTA', max_length=25),
        ),
        migrations.AlterField(
            model_name='acordo',
            name='comprovante_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Disponível para Propostas'), ('EM_NEGOCIACAO', 'Em Negociação'), ('EM_TRANSPORTE', 'Material em Transporte'), ('CONCLUIDO', 'Finalizada')], default='ATIVO', max_length=20),
        ),
    ]
