# Generated by Django 6.0.5 on 2026-06-15 00:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_acordo_entregue_acordo_forma_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordo',
            name='valor_transporte',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddConstraint(
            model_name='acordo',
            constraint=models.CheckConstraint(condition=models.Q(('valor_transporte__gt', 0)), name='valor_transporte_positivo'),
        ),
    ]
